name: "Bf3: Battle Royale"
title: "Bf3: Battle Royale"
description: > # this means to ignore newlines until "show_excerpts:"
  Your favourite last man standing game-mode is finally coming to Bf3 (Venice Unleashed).
tagline: > # this means to ignore newlines until "show_excerpts:"
  Your favourite last man standing game-mode is finally coming to Bf3 (Venice Unleashed).

google_analytics: "UA-192369748-1"

author:
  name: kaloczikvn
  email: kaloczi.kvn@gmail.com

show_excerpts: true
date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spark
  - jekyll-avatar
